language: bash

dist: bionic

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # handle multiple platform
  - docker run --rm --privileged tonistiigi/binfmt:latest --install all
  # install docker buildx
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx install
  - docker buildx create --use

env:
  global:
    - EXTRA_ARGS=--push
  jobs:
    - BUILD_TARGET=debian-buster
    - BUILD_TARGET=debian-buster-slim
    - BUILD_TARGET=debian-stretch
    - BUILD_TARGET=debian-stretch-slim

branches:
  only:
    - main

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make $BUILD_TARGET 2>&1 >/dev/null | grep rust
